### ISSUE TITLE
Truncate HTML case table

### ISSUE THREAD

**Issue by bogosj** [rutherford-nj/data-committee.covid-data#7]
@grecine is it possible to truncate the HTML case tables you generate such that the last row of the table is 3/19/2020, the first reported case in town?

**Comment by grecine** [comment]
fixed in 99a7d54c2737af2cfe428cd9d0cea53d15d5a227

New feature: this cutoff date can be set via an env var called FILE_START_DATE, in string format YYYYMMDD. 20200319 is the default

https://github.com/rutherford-nj/data-committee.covid-data/blob/28ba9079d6d16df858c1e7abc5a780f0375c2fcf/lib/defaults.py#L14
